apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanai-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: oceanai-frontend
  template:
    metadata:
      labels:
        app: oceanai-frontend
    spec:
      containers:
        - name: frontend
          image: oceanai-frontend:latest
          ports:
            - containerPort: 3000
